version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5

#    run production mode in docker
#    networks:
#      - one-network
#
#  nestjs-api:
#    image: nestjs:latest
#    container_name: nestjs-api
#    restart: always
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./.env:/opt/app/.env
#    networks:
#      - one-network
#
#networks:
#  one-network:
#    driver: bridge
